name: Build Check
run-name: GitHub Action Build

on:
  workflow_run:
    workflows: ['Lint Check']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v4

      - name: Install Node Runtime
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Checkout the job
        run: echo "${{job.status}}"
